---
title: "Analysis of chemotherapy trial for colon cancer"
author: "Luoyan Yong"
date: "13/05/2021"
output: html_document
params: 
  age: 20
  data: "data/lung.csv"
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
#load packages
library(dplyr)
library(tidyverse)
library(survival)
library(survminer)
```

## Description of data

```{r raw data, message = FALSE}
dat = read.csv(params$data)
head(dat)
```


```{r summary of data}
summary(dat)
```

## Do females survive longer than males?

```{r survival males vs females}
# compute kaplan-Meier survival estimate
fit <- survfit(Surv(time, status) ~ sex, data = dat)

# Change color, linetype by strata, risk.table color by strata
ggsurvplot(fit,
          pval = TRUE, conf.int = TRUE,
          surv.median.line = "hv", # Specify median survival
          palette = c("#E7B800", "#2E9FDF"))
```


```{r survival ages}
agegp = dat %>% filter(age > params$age)
p = ggsurvplot(survfit(Surv(time, status)~ sex, data = agegp))

```


