---
title: "Analysis of chemotherapy trial for colon cancer dashboard"
output: flexdashboard::flex_dashboard
params: 
  age: 20
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```

```{r, include = FALSE}
#load packages
library(dplyr)
library(tidyverse)
library(survival)
library(survminer)
```

## Do females survive better than males?

```{r}
data(colon)
head(colon)
```

```{r}
# compute kaplan-Meier survival estimate
fit <- survfit(Surv(time, status) ~ sex, data = colon)

# Change color, linetype by strata, risk.table color by strata
ggsurvplot(fit,
          pval = TRUE, conf.int = TRUE,
          surv.median.line = "hv", # Specify median survival
          palette = c("#E7B800", "#2E9FDF"))
```

## Do patients older than a specified age survive less? 
It is also interesting to find out if survival rates of treatment differ between patients with older than `r params$age`

```{r}
agegp = dat %>% filter(age > params$age)
ggsurvplot(survfit(Surv(time, status)~ sex, data = agegp))
```
